# Ansible Collection  requirements 
collections:
  # openstack modules for inventory src
  - name: openstack.cloud
  # community collection for various community modules
  - name: community.general
  # for CA and cert management
  - name: community.crypto
  # ait custom owncloud role and modules
  - name: git@github.com:ait-cs-IaaS/ansible-collection-owncloud.git
    type: git
    version: v0.3.1
# Ansible Role requirements
roles:
  - src: git@github.com:ait-cs-IaaS/ansible-apache2.git
    scm: git
    version: v1.3
    name: apache2

  - src: git@github.com:ait-cs-IaaS/ansible-role-samba.git
    scm: git
    version: v2.7.2
    name: samba
  
  - src: git@github.com:ait-cs-IaaS/ansible-cifs-mounts.git
    scm: git
    version: v1.0
    name: cifs-mounts

  - src: git@github.com:ait-cs-IaaS/ansible-dnsmasq.git
    scm: git
    version: v1.0
    name: dnsmasq

  - src: git@github.com:ait-cs-IaaS/ansible-dovecot.git
    scm: git
    version: v1.2
    name: dovecot

  - src: git@github.com:ait-cs-IaaS/ansible-exim.git
    scm: git
    version: master
    name: exim

  - src: git@github.com:GROG/ansible-role-user.git
    scm: git
    version: master
    name: grog.user

  - src: git@github.com:GROG/ansible-role-group.git
    scm: git
    version: master
    name: grog.group

  - src: git@github.com:GROG/ansible-role-sudo.git
    scm: git
    version: master
    name: grog.sudo

  - src: git@github.com:GROG/ansible-role-authorized-key.git
    scm: git
    version: master
    name: grog.authorized-key

  - src: git@github.com:GROG/ansible-role-package.git
    scm: git
    version: master
    name: GROG.package

  - src: git@github.com:ait-cs-IaaS/ansible-role-maradns.git
    scm: git
    version: v1.1.0
    name: maradns

  - src: git@github.com:ait-cs-IaaS/ansible-python.git
    scm: git
    version: v1.0
    name: python

  - src: git@github.com:ait-cs-IaaS/ansible-openvpn-client.git
    scm: git
    version: v1.1
    name: openvpn-client

  - src: git@github.com:ait-cs-IaaS/ansible-openvpn-server.git
    scm: git
    version: v1.0
    name: openvpn-server

  - src: git@github.com:ait-cs-IaaS/ansible-mariadb.git
    scm: git
    version: v1.0.0
    name: mariadb

  - src: git@github.com:ait-cs-IaaS/ansible-wordpress.git
    scm: git
    version: v1.1.3
    name: wordpress

  - src: git@github.com:owncloud-ansible/owncloud.git
    scm: git
    version: ca2d72effd4dbad1b6d556503d0400c06ed90ea3
    name: owncloud

  - src: git@github.com:owncloud-ansible/php.git
    scm: git
    version: 68b811d4a4f769e7fbb4763ca94e73b1b189ce44
    name: owncloud-php

  - src: git@github.com:owncloud-ansible/apache.git
    scm: git
    version: v1.0.0
    name: owncloud-apache

  - src: git@github.com:owncloud-ansible/mariadb.git
    scm: git
    version: v1.0.0
    name: owncloud-mariadb

  - src: git@github.com:owncloud-ansible/redis.git
    scm: git
    version: v1.0.0
    name: owncloud-redis
  
  - src: git@github.com:ait-cs-IaaS/ansible-horde.git
    scm: git
    version: v1.2.1
    name: horde

  - src: git@github.com:ait-cs-IaaS/ansible-debiansnapshot.git
    scm: git
    version: v1.0
    name: debiansnapshot

  - src: git@github.com:ait-cs-IaaS/ansible-clamav.git
    scm: git
    version: v1.0
    name: clamav

  - src: git@github.com:ait-cs-IaaS/ansible-ca-certs.git
    scm: git
    version: v1.1.0
    name: ca-certs
    
  - src: git@github.com:whotwagner/ansible-role-shorewall.git
    scm: git
    version: v2.0.1
    name: whotwagner.shorewall
  
  - src: git@github.com:ait-cs-IaaS/ansible-kyoushi-simulation.git
    scm: git
    version: v1.1
    name: kyoushi-simulation
  
  - src: git@github.com:ait-cs-IaaS/ansible-auditd.git
    scm: git
    version: v1.0
    name: auditd
  
  - src: git@github.com:ait-cs-IaaS/ansible-suricata.git
    scm: git
    version: v1.1.3
    name: suricata

  - src: git@github.com:ait-cs-IaaS/ansible-kyoushi-gather.git
    scm: git
    version: master
    name: kyoushi-gather

  - name: elastic.beats
    version: 7.9.3

  - src: git@github.com:ait-cs-IaaS/ansible-elastic-beats-modules.git
    scm: git
    version: v1.3
    name: elastic-beats-modules

  - src: git@git-service.ait.ac.at:sct-cyberrange/ansible-roles/logstash.git
    scm: git
    version: v1.2
    name: logstash

  - src: git@github.com:ait-cs-IaaS/ansible-elasticsearch.git
    scm: git
    version: v1.2
    name: elasticsearch

  - src: git@github.com:ait-cs-IaaS/ansible-kibana.git
    scm: git
    version: v1.5.0
    name: kibana

  - src: git@git-service.ait.ac.at:sct-cyberrange/ansible-roles/ansible-passwordlist.git
    scm: git
    version: main
    name: passwordlist
