# https://moz.com/top500 as of 23.02.2020
moz_top500:
  - https://youtube.com
  - http://apple.com
  - https://www.google.com
  - http://www.blogger.com
  - https://microsoft.com
  - http://play.google.com
  - https://support.google.com
  - http://linkedin.com
  - https://maps.google.com
  - http://youtu.be
  - https://wordpress.org
  - http://docs.google.com
  - https://en.wikipedia.org
  - http://cloudflare.com
  - https://mozilla.org
  - http://vimeo.com
  - https://drive.google.com
  - http://plus.google.com
  - https://europa.eu
  - http://adobe.com
  - https://accounts.google.com
  - http://sites.google.com
  - https://googleusercontent.com
  - http://es.wikipedia.org
  - https://uol.com.br
  - http://line.me
  - https://bbc.co.uk
  - http://amazon.com
  - https://istockphoto.com
  - http://bp.blogspot.com
  - https://github.com
  - http://facebook.com
  - https://vk.com
  - http://cnn.com
  - https://www.yahoo.com
  - http://bbc.com
  - https://gstatic.com
  - http://paypal.com
  - https://myspace.com
  - http://feedburner.com
  - https://nih.gov
  - http://t.me
  - https://whatsapp.com
  - http://washingtonpost.com
  - https://google.de
  - http://mail.google.com
  - https://mail.ru
  - http://imdb.com
  - https://dropbox.com
  - http://w3.org
  - https://reuters.com
  - http://nytimes.com
  - https://globo.com
  - http://developers.google.com
  - https://jimdofree.com
  - http://wikimedia.org
  - https://bloomberg.com
  - http://hugedomains.com
  - https://slideshare.net
  - http://issuu.com
  - https://google.es
  - http://get.google.com
  - https://live.com
  - http://creativecommons.org
  - https://dailymotion.com
  - http://msn.com
  - https://opera.com
  - http://medium.com
  - https://policies.google.com
  - http://theguardian.com
  - https://forbes.com
  - http://google.co.jp
  - https://google.com.br
  - http://fr.wikipedia.org
  - https://news.google.com
  - http://pt.wikipedia.org
  - https://elpais.com
  - http://tools.google.com
  - https://translate.google.com
  - http://buydomains.com
  - https://aboutads.info
  - http://huffpost.com
  - https://telegram.me
  - http://google.fr
  - https://latimes.com
  - http://rt.com
  - https://time.com
  - http://it.wikipedia.org
  - https://samsung.com
  - http://namecheap.com
  - https://dan.com
  - http://cpanel.net
  - https://plesk.com
  - http://wsj.com
  - https://office.com
  - http://nasa.gov
  - https://harvard.edu
  - http://news.yahoo.com
  - https://google.pl
  - http://www.wikipedia.org
  - https://independent.co.uk
  - http://huffingtonpost.com
  - https://draft.blogger.com
  - http://ebay.com
  - https://goo.gl
  - http://scribd.com
  - https://usatoday.com
  - http://abcnews.go.com
  - https://cdc.gov
  - http://indiatimes.com
  - https://themeforest.net
  - http://ipv4.google.com
  - https://ft.com
  - http://archive.org
  - https://android.com
  - http://cpanel.com
  - https://change.org
  - http://lefigaro.fr
  - https://twitter.com
  - http://www.gov.uk
  - https://techcrunch.com
  - http://webmd.com
  - https://un.org
  - http://picasaweb.google.com
  - https://rakuten.co.jp
  - http://bit.ly
  - https://youronlinechoices.com
  - http://mirror.co.uk
  - https://ig.com.br
  - http://books.google.com
  - https://wikia.com
  - http://google.co.uk
  - https://marketingplatform.google.com
  - http://businessinsider.com
  - https://ok.ru
  - http://amazon.co.jp
  - https://gravatar.com
  - http://shared.com
  - https://amazon.co.uk
  - http://thesun.co.uk
  - https://cnet.com
  - http://myaccount.google.com
  - https://booking.com
  - http://foxnews.com
  - https://amazon.de
  - http://wired.com
  - https://abril.com.br
  - http://terra.com.br
  - https://google.it
  - http://afternic.com
  - https://mediafire.com
  - http://fandom.com
  - https://aol.com
  - http://hatena.ne.jp
  - https://id.wikipedia.org
  - http://google.ru
  - https://de.wikipedia.org
  - http://steampowered.com
  - https://who.int
  - http://photos.google.com
  - https://fb.com
  - http://aliexpress.com
  - https://files.wordpress.com
  - http://networkadvertising.org
  - https://pinterest.com
  - http://tinyurl.com
  - https://search.google.com
  - http://telegraph.co.uk
  - https://dailymail.co.uk
  - http://yandex.ru
  - https://dw.com
  - http://ox.ac.uk
  - https://academia.edu
  - http://google.co.id
  - https://detik.com
  - http://sciencedirect.com
  - https://naver.com
  - http://gmail.com
  - https://express.co.uk
  - http://ja.wikipedia.org
  - https://ikea.com
  - http://npr.org
  - https://ovh.com
  - http://vice.com
  - https://yahoo.co.jp
  - http://enable-javascript.com	
  - https://britannica.com
  - http://thetimes.co.uk
  - https://lemonde.fr
  - http://google.ca
  - https://kickstarter.com
  - http://surveymonkey.com
  - https://buzzfeed.com
  - http://sapo.pt
  - https://rapidshare.com
  - http://ea.com
  - https://imageshack.us
  - http://cambridge.org
  - https://www.wix.com
  - http://corriere.it
  - https://playstation.com
  - http://engadget.com
  - https://cbsnews.com
  - http://allaboutcookies.org
  - https://groups.google.com
  - http://nokia.com
  - https://columbia.edu
  - http://doubleclick.net
  - https://vox.com
  - http://photos1.blogger.com
  - https://secureserver.net
  - http://hp.com
  - https://nikkei.com
  - http://finance.yahoo.com
  - https://whitehouse.gov
  - http://gnu.org
  - https://ted.com
  - http://google.nl
  - https://mit.edu
  - http://ietf.org
  - https://ria.ru
  - http://list-manage.com
  - https://google.com.tw
  - http://instructables.com
  - https://cnil.fr
  - http://t.co
  - https://twitch.tv
  - http://photobucket.com
  - https://mashable.com
  - http://shopify.com
  - https://amazon.es
  - http://guardian.co.uk
  - https://rambler.ru
  - http://chaturbate.com
  - https://stanford.edu
  - http://wikihow.com
  - https://sputniknews.com
  - http://google.co.in
  - https://oup.com
  - http://eventbrite.com
  - https://disney.com
  - http://groups.yahoo.com
  - https://my.yahoo.com
  - http://nature.com
  - https://espn.com
  - http://bp2.blogger.com
  - https://akamaihd.net
  - http://urbandictionary.com
  - https://metro.co.uk
  - http://welt.de
  - https://cnbc.com
  - http://skype.com
  - https://bloglovin.com
  - http://yadi.sk
  - https://stackoverflow.com
  - http://godaddy.com
  - https://www.over-blog.com
  - http://sciencedaily.com
  - https://bp0.blogger.com
  - http://netvibes.com
  - https://theatlantic.com
  - http://pl.wikipedia.org
  - https://wp.com
  - http://digg.com
  - https://elmundo.es
  - http://theglobeandmail.com
  - https://economist.com
  - http://umich.edu
  - https://depositfiles.com
  - http://asus.com
  - https://sendspace.com
  - http://ru.wikipedia.org
  - https://newyorker.com
  - http://m.wikipedia.org
  - https://ovh.net
  - http://scoop.it
  - https://noaa.gov
  - http://spiegel.de
  - https://nydailynews.com
  - http://newsweek.com
  - https://mozilla.com
  - http://chicagotribune.com
  - https://bandcamp.com
  - http://mysql.com
  - https://ibm.com
  - http://deezer.com
  - https://walmart.com
  - http://ign.com
  - https://princeton.edu
  - http://rottentomatoes.com
  - https://nbcnews.com
  - http://over-blog-kiwi.com
  - https://researchgate.net
  - http://nvidia.com
  - https://abc.net.au
  - http://instagram.com
  - https://cornell.edu
  - http://sedo.com
  - https://gofundme.com
  - http://ziddu.com
  - https://www.weebly.com
  - http://hollywoodreporter.com
  - https://nginx.org
  - http://nypost.com
  - https://mega.nz
  - http://usnews.com
  - https://icann.org
  - http://biglobe.ne.jp
  - https://trustpilot.com
  - http://weibo.com
  - https://tripadvisor.com
  - http://wiley.com
  - https://privacyshield.gov
  - http://smh.com.au
  - https://ovh.co.uk
  - http://yelp.com
  - https://oracle.com
  - http://apache.org
  - https://gizmodo.com
  - http://bing.com
  - https://quora.com
  - http://wa.me
  - https://picasa.google.com
  - http://dell.com
  - https://liveinternet.ru
  - http://bitly.com
  - https://goo.ne.jp
  - http://search.yahoo.com
  - https://ggpht.com
  - http://nationalgeographic.com
  - https://berkeley.edu
  - http://amzn.to
  - https://pbs.org
  - http://theverge.com
  - https://pixabay.com
  - http://example.com
  - https://ytimg.com
  - http://box.com
  - https://forms.gle
  - http://yale.edu
  - https://code.google.com
  - http://about.com
  - https://xbox.com
  - http://netflix.com
  - https://storage.googleapis.com
  - http://goodreads.com
  - https://abc.es
  - http://addtoany.com
  - https://e-recht24.de
  - http://addthis.com
  - https://psychologytoday.com
  - http://zendesk.com
  - https://amazon.fr
  - http://sfgate.com
  - https://utexas.edu
  - http://sciencemag.org
  - https://spotify.com
  - http://discord.gg
  - https://brandbucket.com
  - http://hm.com
  - https://php.net
  - http://washington.edu
  - https://repubblica.it
  - http://loc.gov
  - https://variety.com
  - http://disqus.com
  - https://adssettings.google.com
  - http://greenpeace.org
  - https://nginx.com
  - http://news.com.au
  - https://soundcloud.com
  - http://cbc.ca
  - https://nicovideo.jp
  - http://shutterstock.com
  - https://alibaba.com
  - http://target.com
  - https://unesco.org
  - http://blackberry.com
  - https://interia.pl
  - http://googleblog.com
  - https://orange.fr
  - http://ap.org
  - https://cmu.edu
  - http://ubuntu.com
  - https://ndtv.com
  - http://pcmag.com
  - https://udemy.com
  - http://cocolog-nifty.com	
  - https://m.me
  - http://com.com
  - https://evernote.com
  - http://ca.gov
  - https://parallels.com
  - http://soratemplates.com
  - https://gooyaabitemplates.com
  - http://sina.com.cn
  - https://dreniq.com
  - http://howstuffworks.com
  - https://state.gov
  - http://behance.net
  - https://xinhuanet.com
  - http://scientificamerican.com
  - https://sky.com
  - http://espn.go.com
  - https://entrepreneur.com
  - http://biblegateway.com
  - https://pexels.com
  - http://pinterest.co.uk
  - https://naver.jp
  - http://pastebin.com
  - https://unicef.org
  - http://jstor.org
  - https://feedproxy.google.com
  - http://arstechnica.com
  - https://sports.yahoo.com
  - http://csmonitor.com
  - https://iubenda.com
  - http://daum.net
  - https://alexa.com
  - http://mystrikingly.com
  - https://imageshack.com
  - http://www.livejournal.com
  - https://transandfiestas.ga
  - http://house.gov
  - https://sakura.ne.jp
  - http://last.fm
  - https://elsevier.com
  - http://worldbank.org
  - https://narod.ru
  - http://ftc.gov
  - https://fastcompany.com
  - http://standard.co.uk
  - https://coursera.org
  - http://dribbble.com
  - https://rollingstone.com
  - http://prnewswire.com
  - https://freepik.com
  - http://iso.org
  - https://pewresearch.org
  - http://usgs.gov
  - https://wiktionary.org
  - http://weforum.org
  - https://amazon.ca
  - http://mercurynews.com
  - https://debian.org
  - http://fb.me
  - https://archives.gov
  - http://ehow.com
  - https://about.me
  - http://fortune.com
  - https://a8.net
  - http://fifa.com
  - https://upenn.edu
  - http://blog.fc2.com
  - https://dreamstime.com
  - http://indiegogo.com
  - https://fda.gov
  - http://calendar.google.com
  - https://ieee.org
  - http://amazon.it
  - https://namesilo.com
  - http://arxiv.org
  - https://thoughtco.com
  - http://steamcommunity.com
  - https://billboard.com
  - http://thenextweb.com
  - https://inc.com
  - http://viagens.com.br
  - https://adweek.com
  - http://qz.com
  - https://boston.com
  - http://merriam-webster.com
  - https://ssl-images-amazon.com
  - http://histats.com
  - https://nba.com
  - http://digitaltrends.com
  - https://eonline.com
  - http://amazon.in
  - https://ucoz.ru
  - http://popsugar.com
  - https://stuff.co.nz
  - http://weather.com
  - https://lonelyplanet.com
  - http://techradar.com
  - https://foursquare.com
  - http://megaupload.com
  - https://outlook.com
  - http://thehill.com
  - https://video.google.com
  - http://channel4.com
  - https://excite.co.jp
  - http://teamviewer.com
  - https://thedailybeast.com
  - http://offset.com
  - https://allrecipes.com
  - http://home.neustar
  - https://bp1.blogger.com
  - http://businesswire.com
  - https://psu.edu
  - http://huawei.com